sudo: required
dist: trusty
language: node_js
node_js:
  - 9

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- cd Nimble
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build

notifications:
  email: false
  slack: teamnimble183:rCGT8h8Y90FtX9rro5WXeHDF
    on_success: change
    on_failure: always

script: karma start karma.conf.js --single-run
