export const ICONS: {[key: string]: string} = {
    "icon_add.png": "Add",
    "icon_back.png": "Back",
    "icon_battery.png": "Battery",
    "icon_bookmark.png": "Bookmark",
    "icon_brightness.png": "Brightness",
    "icon_browserchrome.png": "Browser (Chrome)",
    "icon_browserfirefox.png": "Browser (Firefox)",
    "icon_browserinternetexplorer.png": "Browser (Internet Explorer)",
    "icon_browsersafari.png": "Browser (Safari)",
    "icon_camera.png": "Camera",
    "icon_cameraflip.png": "Camera Flip",
    "icon_close.png": "Close",
    "icon_compose.png": "Compose",
    "icon_delete.png": "Delete",
    "icon_download.png": "Download",
    "icon_email.png": "E-mail",
    "icon_emailmac.png": "E-mail",
    "icon_folder.png": "Folder",
    "icon_galleryflower.png": "Gallery",
    "icon_gallerylandscape.png": "Gallery",
    "icon_home.png": "Home",
    "icon_information.png": "Information",
    "icon_menudropdown.png": "Menu (Dropdown)",
    "icon_menuhamburger.png": "Menu (Hamburger)",
    "icon_menuoverflow.png": "Menu Overflow",
    "icon_messaging.png": "Messaging",
    "icon_mute.png": "Mute",
    "icon_pause.png": "Pause",
    "icon_play.png": "Play",
    "icon_print.png": "Print",
    "icon_reply.png": "Reply",
    "icon_save.png": "Save",
    "icon_search.png": "Search",
    "icon_send.png": "Send",
    "icon_settings.png": "Settings",
    "icon_sound.png": "Sound",
    "icon_toggle.png": "Toggle",
    "icon_wifi.png": "WiFi",
    "icon_zoomin.png": "Zoom In",
    "icon_zoomout.png": "Zoom Out"
}
